import js from "@eslint/js";
import checkFile from "eslint-plugin-check-file";
import codeStyle from "eslint-plugin-code-style";
import importX from "eslint-plugin-import-x";
import jsxA11y from "eslint-plugin-jsx-a11y";
import perfectionist from "eslint-plugin-perfectionist";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import globals from "globals";

export default [ // eslint-disable-line
    {
        ignores: [
            ".vite/**/*",
            "build/**",
            "coverage/**/*",
            "dist/**",
            "eslint-rules/**",
            "node_modules/**",
            "public/**/*",
        ],
    },
    js.configs.recommended,
    {
        files: ["**/*.{js,jsx}"],
        languageOptions: {
            ecmaVersion: 2020,
            globals: {
                ...globals.browser,
                ...globals.es2020,
                ...globals.node,
            },
            parserOptions: {
                ecmaFeatures: {
                    jsx: true,
                    modules: true,
                },
            },
            sourceType: "module",
        },
        plugins: {
            "check-file": checkFile,
            "code-style": codeStyle,
            "import-x": importX,
            "jsx-a11y": jsxA11y,
            perfectionist,
            react,
            "react-hooks": reactHooks,
            "simple-import-sort": simpleImportSort,
        },
        rules: {
            ...react.configs.recommended.rules,
            ...reactHooks.configs.recommended.rules,
            "array-callback-return": "off",
            "arrow-body-style": ["error", "as-needed"],
            camelcase: "off",
            "capitalized-comments": ["error"],
            "check-file/filename-naming-convention": [
                "error",
                { "**/*.{js,jsx}": "KEBAB_CASE" },
                { ignoreMiddleExtensions: true },
            ],
            "check-file/folder-naming-convention": [
                "error",
                { "src/**": "KEBAB_CASE" },
            ],
            "code-style/absolute-imports-only": "error",
            "code-style/array-items-per-line": "error",
            "code-style/array-objects-on-new-lines": "error",
            "code-style/arrow-function-block-body": "error",
            "code-style/arrow-function-simple-jsx": "error",
            "code-style/arrow-function-simplify": "error",
            "code-style/assignment-value-same-line": "error",
            "code-style/block-statement-newlines": "error",
            "code-style/comment-spacing": "error",
            "code-style/curried-arrow-same-line": "error",
            "code-style/export-format": "error",
            "code-style/function-call-spacing": "error",
            "code-style/function-naming-convention": "error",
            "code-style/function-params-per-line": "error",
            "code-style/hook-callback-format": "error",
            "code-style/hook-deps-per-line": "error",
            "code-style/if-statement-format": "error",
            "code-style/import-format": "error",
            "code-style/import-source-spacing": "error",
            "code-style/index-export-style": "error",
            "code-style/jsx-children-on-new-line": "error",
            "code-style/jsx-closing-bracket-spacing": "error",
            "code-style/jsx-element-child-new-line": "error",
            "code-style/jsx-logical-expression-simplify": "error",
            "code-style/jsx-parentheses-position": "error",
            "code-style/jsx-prop-naming-convention": "error",
            "code-style/jsx-simple-element-one-line": "error",
            "code-style/jsx-string-value-trim": "error",
            "code-style/jsx-ternary-format": "error",
            "code-style/member-expression-bracket-spacing": "error",
            "code-style/module-index-exports": "error",
            "code-style/multiline-argument-newline": "error",
            "code-style/multiline-if-conditions": "error",
            "code-style/multiple-arguments-per-line": "error",
            "code-style/nested-call-closing-brackets": "error",
            "code-style/no-empty-lines-in-function-calls": "error",
            "code-style/no-empty-lines-in-function-params": "error",
            "code-style/no-empty-lines-in-jsx": "error",
            "code-style/no-empty-lines-in-objects": "error",
            "code-style/no-empty-lines-in-switch-cases": "error",
            "code-style/object-property-per-line": "error",
            "code-style/object-property-value-brace": "error",
            "code-style/object-property-value-format": "error",
            "code-style/opening-brackets-same-line": "error",
            "code-style/simple-call-single-line": "error",
            "code-style/single-argument-on-one-line": "error",
            "code-style/string-property-spacing": "error",
            "code-style/variable-naming-convention": "error",
            "comma-dangle": ["error", "always-multiline"],
            "comma-spacing": ["error",
                {
                    after: true,
                    before: false,
                },
            ],
            complexity: "off",
            "consistent-return": "off",
            curly: ["error", "multi-or-nest"],
            "default-case": "off",
            "default-param-last": 0,
            "dot-location": ["error", "object"],
            "dot-notation": ["error", { allowKeywords: false }],
            eqeqeq: "error",
            "func-style": ["error", "expression"],
            "function-call-argument-newline": ["error", "always"],
            "function-paren-newline": "off",
            "import-x/no-cycle": 0,
            "import-x/no-default-export": "error",
            "import-x/no-named-as-default": 0,
            "import-x/no-named-as-default-member": 0,
            "import-x/no-unresolved": 0,
            "import-x/prefer-default-export": 0,
            indent: ["error", 4],
            "jsx-a11y/anchor-is-valid": "off",
            "jsx-a11y/click-events-have-key-events": "off",
            "jsx-a11y/html-has-lang": "off",
            "jsx-a11y/label-has-associated-control": "off",
            "jsx-a11y/media-has-caption": "off",
            "jsx-a11y/no-static-element-interactions": "off",
            "jsx-a11y/tabindex-no-positive": "off",
            "jsx-quotes": ["error", "prefer-double"],
            "key-spacing": ["error",
                {
                    afterColon: true,
                    beforeColon: false,
                },
            ],
            "linebreak-style": "off",
            "max-depth": ["error", 4],
            "max-len": "off",
            "max-lines": "off",
            "max-lines-per-function": "off",
            "max-nested-callbacks": ["error", 4],
            "max-params": "off",
            "multiline-comment-style": ["error", "bare-block"],
            "no-alert": "error",
            "no-await-in-loop": "error",
            "no-cond-assign": "error",
            "no-else-return": "error",
            "no-eq-null": "error",
            "no-extra-semi": "error",
            "no-fallthrough": "error",
            "no-inline-comments": "error",
            "no-irregular-whitespace": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-multi-spaces": "error",
            "no-multiple-empty-lines": [
                "error",
                {
                    max: 1,
                    maxBOF: 0,
                    maxEOF: 0,
                },
            ],
            "no-nested-ternary": "off",
            "no-plusplus": "error",
            "no-redeclare": "error",
            "no-return-assign": "off",
            "no-self-compare": "error",
            "no-unexpected-multiline": "error",
            "no-unused-vars": "error",
            "no-use-before-define": "error",
            "no-useless-escape": "off",
            "no-var": "error",
            "nonblock-statement-body-position": ["error", "beside"],
            "object-curly-newline": [
                "error",
                {
                    ExportDeclaration: { // eslint-disable-line
                        minProperties: 4,
                        multiline: true,
                    },
                    ImportDeclaration: { // eslint-disable-line
                        minProperties: 4,
                        multiline: true,
                    },
                    ObjectExpression: {
                        minProperties: 2,
                        multiline: true,
                    },
                    ObjectPattern: {
                        minProperties: 2,
                        multiline: true,
                    },
                },
            ],
            "object-curly-spacing": ["error", "always"],
            "object-property-newline": [
                "error",
                { allowAllPropertiesOnSameLine: false },
            ],
            "padded-blocks": ["error", "never"],
            "padding-line-between-statements": [
                "error",
                {
                    blankLine: "always",
                    next: "return",
                    prev: "*",
                },
                {
                    blankLine: "always",
                    next: "*",
                    prev: ["const", "let", "var"],
                },
                {
                    blankLine: "always",
                    next: "*",
                    prev: "expression",
                },
                {
                    blankLine: "always",
                    next: "expression",
                    prev: "expression",
                },
                {
                    blankLine: "always",
                    next: "export",
                    prev: "export",
                },
            ],
            "perfectionist/sort-array-includes": [
                "error",
                {
                    order: "asc",
                    type: "natural",
                },
            ],
            "perfectionist/sort-maps": [
                "error",
                {
                    order: "asc",
                    type: "natural",
                },
            ],
            "perfectionist/sort-objects": [
                "error",
                {
                    ignoreCase: false,
                    order: "asc",
                    type: "natural",
                },
            ],
            "perfectionist/sort-sets": [
                "error",
                {
                    order: "asc",
                    type: "natural",
                },
            ],
            "perfectionist/sort-switch-case": [
                "error",
                {
                    order: "asc",
                    type: "natural",
                },
            ],
            "perfectionist/sort-variable-declarations": [
                "error",
                {
                    order: "asc",
                    type: "natural",
                },
            ],
            quotes: ["error", "double"],
            radix: 0,
            "react-hooks/exhaustive-deps": "off",
            "react-hooks/set-state-in-effect": 0,
            "react-hooks/use-memo": 0,
            "react/button-has-type": 0,
            "react/display-name": "off",
            "react/forbid-prop-types": 0,
            "react/function-component-definition": [
                "error",
                {
                    namedComponents: "arrow-function",
                    unnamedComponents: "arrow-function",
                },
            ],
            "react/jsx-closing-bracket-location": ["error", "line-aligned"],
            "react/jsx-closing-tag-location": "error",
            "react/jsx-curly-spacing": ["error",
                {
                    "children": true,
                    "when": "never",
                },
            ],
            "react/jsx-equals-spacing": ["error", "never"],
            "react/jsx-filename-extension": [1, { extensions: [".js", ".jsx"] }],
            "react/jsx-first-prop-new-line": ["error", "multiline"],
            "react/jsx-indent": ["error", 4],
            "react/jsx-indent-props": ["error", 4],
            "react/jsx-max-props-per-line": ["error", { maximum: 1 }],
            "react/jsx-newline": ["error", { prevent: true }],
            "react/jsx-one-expression-per-line": ["error", { allow: "single-child" }],
            "react/jsx-props-no-spreading": "off",
            "react/jsx-sort-props": [
                2,
                {
                    callbacksLast: true,
                    ignoreCase: false,
                    locale: "auto",
                    multiline: "last",
                    noSortAlphabetically: false,
                    shorthandFirst: false,
                    shorthandLast: true,
                },
            ],
            "react/jsx-wrap-multilines": [
                "error",
                {
                    arrow: "parens-new-line",
                    assignment: "parens-new-line",
                    condition: "parens-new-line",
                    declaration: "parens-new-line",
                    logical: "parens-new-line",
                    prop: "parens-new-line",
                    return: "parens-new-line",
                },
            ],
            "react/no-danger": 0,
            "react/prop-types": 0,
            "react/react-in-jsx-scope": "off",
            "react/require-default-props": 0,
            "react/self-closing-comp": ["error",
                {
                    "component": true,
                    "html": true,
                },
            ],
            semi: ["error", "always"],
            "semi-spacing": ["error",
                {
                    "after": true,
                    "before": false,
                },
            ],
            "simple-import-sort/exports": "error",
            "simple-import-sort/imports": "error",
            "sort-keys": "off",
            "space-in-parens": ["error", "never"],
            "space-infix-ops": ["error", { "int32Hint": false }],
            "valid-typeof": "error",
            "vars-on-top": "error",
        },
        settings: {
            "import-x/extensions": [".js", ".jsx"],
            "import-x/resolver": {
                node: {
                    extensions: [".js", ".jsx"],
                    paths: ["src"],
                },
            },
            react: { version: "detect" },
        },
    },
    {
        files: ["**/index.{js,jsx}"],
        rules: {
            "padding-line-between-statements": [
                "error",
                {
                    blankLine: "always",
                    next: "return",
                    prev: "*",
                },
                {
                    blankLine: "always",
                    next: "*",
                    prev: ["const", "let", "var"],
                },
                {
                    blankLine: "always",
                    next: "*",
                    prev: "expression",
                },
                {
                    blankLine: "always",
                    next: "expression",
                    prev: "expression",
                },
            ],
        },
    },
];
